spring:
  application:
    name: newsTHINKY-BE

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 서버에서 인증 코드를 요청할 url
            token-uri: https://kauth.kakao.com/oauth/token #액세스 토큰을 요청하기 위한 url
            user-info-uri: https://kapi.kakao.com/v2/user/me #액세스 토큰을 바탕으로 사용자의 정보를 받아오기 위한 url
            user-name-attribute: id
        registration:
          kakao:
            client-id: 32922604eb4a85c6693fc7db4af7535a
            client-secret: WTY1y5weAUw9jpAN13s1J7bCvXaAsuNQ
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email


  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client: DEBUG

jwt:
  key: newsTHINKYpasswordSHhhhhnewsTHINKYpasswordSHhhhhnewsTHINKYpasswordSHhhhhnewsTHINKYpasswordSHhhhh

